import { Request, Response } from 'express';
import CreateImageRequest from '../dtos/save-image-request';
import { saveImage, getImage } from '../daos/dao';
import { getResponse } from '../utilities/web-utils';
import Image from '../entities/image';

const EMPTY_ID:string = "";

export const saveImageHandler = (req: Request, res: Response) => {
    saveImage(getImageObjFromRequest(req), (imageId:string):any =>{
        res.json(getResponse(imageId));
    });
};

const getImageObjFromRequest = (req: Request):Image => {
    const request:CreateImageRequest = new CreateImageRequest(req.body);
    const uploadInformation = req.file;
    
    console.log("save image request body: "+JSON.stringify(request));
    console.log("uploadInformation: "+JSON.stringify(uploadInformation));

    const image = new Image(
        /* id will be generated by the DAO layer */
        EMPTY_ID,
        request.userId, 
        request.title,
        request.description,
        uploadInformation.originalname,
        uploadInformation.filename,
        uploadInformation.path
    );

    return image;
}

export const getImageHandler = (req: Request, res: Response) => {
    const imageId:string = req.params.id;

    getImage(imageId,(image:Image)=>{
        res.json(getResponse(image));
    });
};